name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSL
        run: |
          apt-get update
          apt-get install -y libssl-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./apps/server/backend

      - name: Generate Prisma Client
        run: pnpm db:generate
        working-directory: ./apps/server/backend

      - name: Build backend
        run: pnpm run build
        working-directory: ./apps/server/backend

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-backend
          path: ./apps/server/backend/dist
