name: Build And Push To Docker Hub

on:
  create:
    branches:
      - "v-*"

jobs:
  pushToHub:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub using PAT
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get verison from package.json
        id: version
        run: echo ::set-output name=version::$(node -p "require('./apps/web/package.json').version")

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-web-v${{ steps.version.outputs.version }} -t ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-web:latest -f noterai/apps/web/dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-web-v${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-web:latest

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-backend-v${{ steps.version.outputs.version }} -t ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-backend:latest -f noterai/apps/backend/dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-backend-v${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/noterai:noterai-backend:latest
